### ISSUE TITLE
Running from Linux shell without X11 raises exception

### ISSUE THREAD

**Issue by sglebs** [sglebs/srccheck#32]
```
Traceback (most recent call last):
File "/usr/bin/srccheck", line 9, in <module>
load_entry_point('srccheck==0.0.7', 'console_scripts', 'srccheck')()
File "/usr/lib/python3.4/site-packages/utilities/srccheck.py", line 358, in main
[violation_count, file_tracked_metrics] = process_file_metrics(db, arguments)
File "/usr/lib/python3.4/site-packages/utilities/srccheck.py", line 287, in process_file_metrics
return process_generic_metrics(db,cmdline_arguments,"--maxFileMetrics", cmdline_arguments["--fileQuery"], _print_file_violation, cmdline_arguments.get("--regexIgnoreFiles", None), "File")
File "/usr/lib/python3.4/site-packages/utilities/srccheck.py", line 261, in process_generic_metrics
scope_name)
File "/usr/lib/python3.4/site-packages/utilities/utils.py", line 83, in save_histogram
plt.figure() # new one, or they will be mixed
File "/usr/lib64/python3.4/site-packages/matplotlib/pyplot.py", line 535, in figure
**kwargs)
File "/usr/lib64/python3.4/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
return new_figure_manager_given_figure(num, figure)
File "/usr/lib64/python3.4/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
window = Tk.Tk()
File "/usr/lib64/python3.4/tkinter/__init__.py", line 1856, in __init__
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

```

**Comment by sglebs** [comment]
The problem: http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined

Backends: http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
